# Generated by Django 4.0.2 on 2022-03-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estate',
            constraint=models.UniqueConstraint(fields=('national_number', 'address'), name='unique_code_address'),
        ),
    ]
