# Generated by Django 4.0.2 on 2022-04-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realty',
            options={'ordering': ['code'], 'permissions': [('activate_realty', 'Can activate realty.')], 'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
    ]
