# Generated by Django 4.0.2 on 2022-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_estate_total_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='national_number',
            field=models.PositiveBigIntegerField(verbose_name='Número Predial Nacional'),
        ),
    ]
