# Generated by Django 4.0.2 on 2022-03-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_estate_state_alter_estate_appraisal_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'permissions': [('activate_estate', 'Can activate estate.')], 'verbose_name': 'Predio', 'verbose_name_plural': 'Predios'},
        ),
        migrations.AlterModelOptions(
            name='realty',
            options={'permissions': [('activate_realty', 'Can activate realty.')], 'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
    ]
