# Generated by Django 4.0.2 on 2022-03-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_estate_unique_code_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='realty',
            constraint=models.UniqueConstraint(fields=('code', 'address'), name='realty_unique_code_address'),
        ),
    ]
