# Generated by Django 4.0.2 on 2022-03-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_estate_national_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='national_number',
            new_name='national_number_1',
        ),
    ]
