# Generated by Django 4.0.2 on 2022-03-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_national_number_estate_national_number_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='national_number_2',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Número Predial Nacional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='national_number_3',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Número Predial Nacional'),
            preserve_default=False,
        ),
    ]
