# Generated by Django 4.0.2 on 2022-03-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Número DI')),
                ('id_type', models.PositiveSmallIntegerField(choices=[(0, 'CC'), (1, 'NIT'), (2, 'TI'), (3, 'CE')], verbose_name='Tipo DI')),
                ('person_type', models.PositiveSmallIntegerField(choices=[(0, 'Natural'), (1, 'Legal')], verbose_name='Tipo Persona')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Legal',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('person_legal_type', models.PositiveSmallIntegerField(choices=[(0, 'S.A.'), (1, 'S.A.S'), (2, 'LTDA.'), (3, 'E.U.'), (4, '& CIA.'), (5, 'S. en C.')], verbose_name='Tipo de Sociedad')),
            ],
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='Person_Natural',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('last_name', models.CharField(max_length=64, verbose_name='Apellido(s)')),
            ],
            bases=('people.person',),
        ),
    ]
