# Generated by Django 4.0.2 on 2022-03-02 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Número DI')),
                ('id_type', models.PositiveSmallIntegerField(choices=[(0, 'CC'), (1, 'NIT'), (2, 'TI'), (3, 'CE')], verbose_name='Tipo DI')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Natural'), (1, 'Legal')], verbose_name='Tipo Persona')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Legal',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('legal_type', models.PositiveSmallIntegerField(choices=[(0, 'S.A.'), (1, 'S.A.S'), (2, 'LTDA.'), (3, 'E.U.'), (4, '& CIA.'), (5, 'S. en C.')], verbose_name='Tipo de Sociedad')),
            ],
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='Person_Natural',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('last_name', models.CharField(max_length=64, verbose_name='Apellido(s)')),
            ],
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='Person_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.PositiveSmallIntegerField(choices=[(0, 'Personal'), (1, 'Residencia'), (2, 'Auxiliar Administrativo'), (3, 'Auxiliar Contable')], verbose_name='Uso')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Persona')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.phone', verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.PositiveSmallIntegerField(choices=[(0, 'Principal'), (1, 'Adicional')], verbose_name='Uso')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.email', verbose_name='Correo Electrónico')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.PositiveSmallIntegerField(choices=[(0, 'Residencia'), (1, 'Trabajo'), (2, 'Planta'), (3, 'Administración'), (4, 'Punto de Venta')], verbose_name='Uso')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.address', verbose_name='Dirección')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Persona')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ManyToManyField(related_name='people', related_query_name='person', through='people.Person_Address', to='references.Address', verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.ManyToManyField(related_name='people', related_query_name='person', through='people.Person_Email', to='references.Email', verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ManyToManyField(related_name='people', related_query_name='person', through='people.Person_Phone', to='references.Phone', verbose_name='Teléfono'),
        ),
    ]
