# Generated by Django 4.0.2 on 2022-03-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.PositiveSmallIntegerField(choices=[(0, 'Personal'), (1, 'Residencia'), (2, 'Auxiliar Administrativo'), (3, 'Auxiliar Contable')], verbose_name='Tipo')),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='person_legal',
            old_name='person_legal_type',
            new_name='legal_type',
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ManyToManyField(related_name='phones', related_query_name='phone', through='people.Person_Phone', to='phones.Phone', verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='person_phone',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='person_phone',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.phone', verbose_name='Teléfono'),
        ),
    ]
