# Generated by Django 4.0.2 on 2022-03-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('activate_person', 'Can activate inactive person.')], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
