# Generated by Django 4.0.2 on 2022-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='complete_name',
            field=models.CharField(default=None, max_length=128, verbose_name='Nombre Completo'),
            preserve_default=False,
        ),
    ]
