# Generated by Django 4.0.2 on 2022-03-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person_legal_person_natural',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.ManyToManyField(blank=True, related_name='people', related_query_name='person', through='people.Person_Phone', to='references.Phone', verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='person_legal_person_natural',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person_legal', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='person_legal_person_natural',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person_natural', verbose_name='Personal'),
        ),
    ]
