# Generated by Django 4.0.2 on 2022-04-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person_address',
            index=models.Index(fields=['person', 'address'], name='people_pers_person__f7b691_idx'),
        ),
    ]
