# Generated by Django 4.0.2 on 2022-03-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Legal_Person_Natural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.PositiveSmallIntegerField(choices=[(0, 'Representate Legal'), (1, 'Gerente General'), (2, 'Suplente'), (3, 'Auxiliar Administración'), (4, 'Auxialr Contabilidad'), (5, 'Supervisor Planta'), (6, 'Socio')], verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Persona Natural con Cargo en Persona Jurídica',
                'verbose_name_plural': 'Personas Naturales con Cargos en Personas Jurídicas',
            },
        ),
        migrations.AddField(
            model_name='person_legal',
            name='staff',
            field=models.ManyToManyField(related_name='people_legal', related_query_name='person_legal', through='people.Person_Legal_Person_Natural', to='people.Person_Natural', verbose_name='Personal'),
        ),
        migrations.AddField(
            model_name='person_legal_person_natural',
            name='person_legal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person_legal', verbose_name='Persona Jurídica'),
        ),
        migrations.AddField(
            model_name='person_legal_person_natural',
            name='person_natural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person_natural', verbose_name='Persona Natural'),
        ),
        migrations.AddConstraint(
            model_name='person_legal_person_natural',
            constraint=models.UniqueConstraint(fields=('person_legal', 'person_natural'), name='unique_person_legal_person_natural'),
        ),
    ]
