# Generated by Django 4.0.2 on 2022-04-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_address_people_pers_person__f7b691_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['complete_name'], 'permissions': [('activate_person', 'Can activate person.')], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='person_legal',
            options={'ordering': ['complete_name'], 'verbose_name': 'Persona Jurídica', 'verbose_name_plural': 'Personas Jurídicas'},
        ),
        migrations.AlterModelOptions(
            name='person_natural',
            options={'ordering': ['complete_name'], 'verbose_name': 'Persona Natural', 'verbose_name_plural': 'Personas Naturales'},
        ),
        migrations.RemoveIndex(
            model_name='person_address',
            name='people_pers_person__f7b691_idx',
        ),
    ]
