# Generated by Django 4.0.2 on 2022-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('people', '0002_alter_person_legal_person_natural_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='people', related_query_name='person', through='people.Person_Address', to='references.Address', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='person',
            name='e_mail',
            field=models.ManyToManyField(blank=True, related_name='people', related_query_name='person', through='people.Person_E_Mail', to='references.E_Mail', verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='person_legal',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='people_legal', related_query_name='person_legal', through='people.Person_Legal_Person_Natural', to='people.Person_Natural', verbose_name='Personal'),
        ),
    ]
