# Generated by Django 4.0.2 on 2022-03-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_options_alter_person_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person_address',
            options={'verbose_name': 'Dirección Persona', 'verbose_name_plural': 'Direcciones Personas'},
        ),
        migrations.AlterModelOptions(
            name='person_e_mail',
            options={'verbose_name': 'Correo Electrónico Personas', 'verbose_name_plural': 'Correos Electrónicos Personas'},
        ),
        migrations.AlterModelOptions(
            name='person_legal_person_natural',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='person_phone',
            options={'verbose_name': 'Teléfono Persona', 'verbose_name_plural': 'Teléfonos Personas'},
        ),
    ]
