# Generated by Django 4.0.2 on 2022-04-13 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0002_charge_factor_factor_data_and_more'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Template',
            fields=[
                ('state_change_date', models.DateTimeField(auto_now=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1)),
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ledger_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers_templates', related_query_name='ledger_template', to='accounting.ledger_type', verbose_name='Tipo Registro')),
                ('state_change_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers_templates', related_query_name='ledger_template', to='references.transaction_type', verbose_name='Tipo Transacción')),
            ],
            options={
                'verbose_name': 'Formato Registro',
                'verbose_name_plural': 'Formatos Registros',
            },
        ),
        migrations.CreateModel(
            name='Charge_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_change_date', models.DateTimeField(auto_now=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1)),
                ('nature', models.PositiveIntegerField(choices=[(-1, 'Crédito'), (1, 'Débito')], verbose_name='Naturaleza')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_templates', related_query_name='charge_template', to='accounting.account', verbose_name='Cuenta')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_templates', related_query_name='charge_template', to='references.charge_factor', verbose_name='Factor')),
                ('ledger_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_templates', related_query_name='charge_template', to='accounting.ledger_template', verbose_name='Formato Registro')),
                ('state_change_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formato Movimiento',
                'verbose_name_plural': 'Formatos Movimientos',
            },
        ),
    ]
