# Generated by Django 4.0.2 on 2022-04-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_charge_template_factor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledger_template',
            constraint=models.UniqueConstraint(fields=('transaction_type', 'ledger_type'), name='unique_trancaction_ledger_types'),
        ),
    ]
