# Generated by Django 4.0.2 on 2022-04-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_ledger_template_charge_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_template',
            name='nature',
            field=models.IntegerField(choices=[(-1, 'Crédito'), (1, 'Débito')], verbose_name='Naturaleza'),
        ),
    ]
