# Generated by Django 4.0.2 on 2022-04-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledger_template_unique_trancaction_ledger_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('activate_account', 'Can activate account.'), ('view_balance', 'Can view balance.')], 'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
