# Generated by Django 4.0.2 on 2022-04-13 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge_Factor',
            fields=[
                ('state_change_date', models.DateTimeField(auto_now=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1)),
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('state_change_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factor Movimiento',
                'verbose_name_plural': 'Factores Moviminetos',
                'permissions': [('charge_factor', 'Can activate charge factor.')],
            },
        ),
        migrations.CreateModel(
            name='Factor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_change_date', models.DateTimeField(auto_now=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1)),
                ('validity_date', models.DateField(verbose_name='Fecha Validez')),
                ('amount', models.PositiveIntegerField(verbose_name='Monto')),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Porcentaje')),
                ('in_instance_attribute', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Atributo en Instancia')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datas', related_query_name='data', to='references.charge_factor')),
                ('state_change_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Factor',
                'verbose_name_plural': 'Datos Factores',
            },
        ),
        migrations.AddConstraint(
            model_name='factor_data',
            constraint=models.UniqueConstraint(fields=('factor', 'validity_date'), name='unique_factor_validity'),
        ),
        migrations.AddConstraint(
            model_name='factor_data',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='facdat_percentage_gte_0_and_lte_100'),
        ),
    ]
