# Generated by Django 4.0.2 on 2022-04-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['code'], 'permissions': [('address', 'Can activate address.')], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
    ]
