# Generated by Django 4.0.2 on 2022-04-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge_factor',
            options={'permissions': [('activate_charge_factor', 'Can activate charge factor.')], 'verbose_name': 'Factor Movimiento', 'verbose_name_plural': 'Factores Movimientos'},
        ),
    ]
