# Generated by Django 4.0.2 on 2022-03-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_address_state_alter_e_mail_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'permissions': [('address', 'Can activate address.')], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='e_mail',
            options={'permissions': [('e_mail', 'Can activate e-mail.')], 'verbose_name': 'Correo Electrónico', 'verbose_name_plural': 'Correos Electrónicos'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'permissions': [('activate_phone', 'Can activate phone.')], 'verbose_name': 'Teléfono', 'verbose_name_plural': 'Teléfonos'},
        ),
        migrations.AlterModelOptions(
            name='transaction_type',
            options={'permissions': [('activate_transaction_type', 'Can activate transaction type.')], 'verbose_name': 'Transacción Tipo', 'verbose_name_plural': 'Transacciones Tipos'},
        ),
    ]
