# Generated by Django 4.0.2 on 2022-04-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e_mail',
            options={'ordering': ['e_mail'], 'permissions': [('e_mail', 'Can activate e-mail.')], 'verbose_name': 'Correo Electrónico', 'verbose_name_plural': 'Correos Electrónicos'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['code'], 'permissions': [('activate_phone', 'Can activate phone.')], 'verbose_name': 'Teléfono', 'verbose_name_plural': 'Teléfonos'},
        ),
    ]
