# Generated by Django 4.0.2 on 2022-04-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_charge_factor_factor_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge_factor',
            options={'permissions': [('charge_factor', 'Can activate charge factor.')], 'verbose_name': 'Factor Movimiento', 'verbose_name_plural': 'Factores Movimientos'},
        ),
    ]
