# Generated by Django 4.0.2 on 2022-03-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease_realty',
            options={'permissions': [('activate_lease_realty', 'Can activate lease realty.')], 'verbose_name': 'Arriendo Inmueble', 'verbose_name_plural': 'Arriendos Inuembles'},
        ),
    ]
