# Generated by Django 4.0.3 on 2022-04-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('accountables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease_realty_person',
            name='e_mail',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.e_mail', verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='lease_realty_person',
            name='phone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.phone', verbose_name='Teléfono'),
        ),
    ]
