# Generated by Django 4.0.2 on 2022-03-23 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease_realty',
            name='id',
        ),
        migrations.AddField(
            model_name='lease_realty',
            name='accountable_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accountables.accountable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease_realty_person',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1, editable=False),
        ),
        migrations.AddField(
            model_name='lease_realty_person',
            name='state_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lease_realty_person',
            name='state_change_user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease_realty_realty',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1, editable=False),
        ),
        migrations.AddField(
            model_name='lease_realty_realty',
            name='state_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lease_realty_realty',
            name='state_change_user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
