# Generated by Django 4.0.2 on 2022-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountable',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1),
        ),
        migrations.AlterField(
            model_name='date_value',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1),
        ),
        migrations.AlterField(
            model_name='lease_realty_person',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1),
        ),
        migrations.AlterField(
            model_name='lease_realty_realty',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Por Correguir'), (2, 'Por Revisar'), (3, 'Revisado')], default=1),
        ),
    ]
