# Generated by Django 4.0.2 on 2022-03-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
        ('accountables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease_realty',
            name='part',
            field=models.ManyToManyField(related_name='leases_realties', related_query_name='lease_realty', through='accountables.Lease_Realty_Person', to='people.Person', verbose_name='Parte'),
        ),
        migrations.AlterField(
            model_name='lease_realty',
            name='realty',
            field=models.ManyToManyField(related_name='leases_realties', related_query_name='lease_realty', through='accountables.Lease_Realty_Realty', to='properties.Realty', verbose_name='Inmueble'),
        ),
        migrations.AlterField(
            model_name='lease_realty_person',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_realties_people', related_query_name='lease_realty_person', to='accountables.lease_realty', verbose_name='Contrato'),
        ),
    ]
