# Generated by Django 4.0.2 on 2022-04-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('accountables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease_realty_person',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_realties_people', related_query_name='lease_realty_person', to='references.address', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='lease_realty_person',
            name='e_mail',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases_realties_people', related_query_name='lease_realty_person', to='references.e_mail', verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='lease_realty_person',
            name='phone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases_realties_people', related_query_name='lease_realty_person', to='references.phone', verbose_name='Teléfono'),
        ),
    ]
