# Generated by Django 4.0.2 on 2022-04-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountables', '0002_alter_lease_realty_person_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease_realty_person',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountables.lease_realty', verbose_name='Contrato'),
        ),
    ]
